<?php

/**
 * @file
 * Allows Twitter users to tweet directly from within your Drupal website.
 */

/**
 * Implementation of hook_block_info().
 */
function birdbox_block_info() {
  $blocks = array();
  $blocks['tweet'] = array(
    'info' => t('Birdbox'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function birdbox_block_view($delta = '') {
  $block = array();
  if ($delta == 'tweet') {
    $block['subject'] = t('Birdbox');
    $block['content'] = drupal_get_form('birdbox_tweet_form');
  }
  return $block;
}

/**
 * Form for tweeting.
 */
function birdbox_tweet_form($form_state) {
  
  // If we don't have a configured Twitter consumer key and secret, we won't show the form.
  $key = variable_get('twitter_consumer_key', '');
  $secret = variable_get('twitter_consumer_secret', '');
  if ($key == '' || $secret == '') {
    drupal_set_message(
      t('Please <a href="@configure-url">configure</a> your Twitter consumer key and secret.', 
        array(
          '!configure-url' => url('admin/config/services/twitter'),
        )
      ), 
      'error');
    return NULL;
  }
  
  // Consumer key and secret are okay, let's see that form!
  $form = array();
  $form['tweet_text'] = array(
    '#type' => 'textarea',
    '#title' => t('What\'s happening?'),
    '#rows' => 1,
    '#required' => TRUE,
  );
  $form['tweet_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Tweet'),
  );
  return $form;
}


/**
 * Submit handler for the tweet form.
 */
function birdbox_tweet_form_submit($form, &$form_state) {
  $sid = session_api_get_sid();
  // Now go for the authorization.
  birdbox_tweet_authorize($sid);
}

/**
 * Authorization request for Twitter.
 */
function birdbox_tweet_authorize($sid) {
  module_load_include('lib.php', 'oauth_common');
  module_load_include('lib.php', 'twitter');

  $twitter = new TwitterOAuth(variable_get('twitter_consumer_key'), variable_get('twitter_consumer_secret'));
  $token = $twitter->get_request_token();

  $_SESSION['twitter_oauth']['sid'] = $sid;  
  $_SESSION['twitter_oauth']['token'] = $token;
  $_SESSION['twitter_oauth']['destination'] = $_GET['q'];
  drupal_goto($twitter->get_authorize_url($token));
}

